Update kubernetes-manifests.yaml

diff --git a/release/without-istio/kubernetes-manifests.yaml b/release/without-istio/kubernetes-manifests.yaml
--- a/release/without-istio/kubernetes-manifests.yaml
+++ b/release/without-istio/kubernetes-manifests.yaml
@@ -695,37 +695,37 @@ spec:
         runAsGroup: 1000
         runAsNonRoot: true
         runAsUser: 1000
-      initContainers:
-      - command:
-        - /bin/sh
-        - -exc
-        - |
-          MAX_RETRIES=12
-          RETRY_INTERVAL=10
-          for i in $(seq 1 $MAX_RETRIES); do
-            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
-            STATUSCODE=$(curl -s -o /dev/null -w "%{http_code}" http://${FRONTEND_ADDR})
-            if [ $STATUSCODE -eq 200 ]; then
-                echo "Frontend is reachable."
-                exit 0
-            fi
-            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-            sleep $RETRY_INTERVAL
-          done
-          echo "Failed to reach frontend after $MAX_RETRIES attempts."
-          exit 1
-        name: frontend-check
-        securityContext:
-          allowPrivilegeEscalation: false
-          capabilities:
-            drop:
-              - ALL
-          privileged: false
-          readOnlyRootFilesystem: true
-        image: curlimages/curl:latest
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
+      # initContainers:
+      # - command:
+      #   - /bin/sh
+      #   - -exc
+      #   - |
+      #     MAX_RETRIES=12
+      #     RETRY_INTERVAL=10
+      #     for i in $(seq 1 $MAX_RETRIES); do
+      #       echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
+      #       STATUSCODE=$(curl -s -o /dev/null -w "%{http_code}" http://${FRONTEND_ADDR})
+      #       if [ $STATUSCODE -eq 200 ]; then
+      #           echo "Frontend is reachable."
+      #           exit 0
+      #       fi
+      #       echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+      #       sleep $RETRY_INTERVAL
+      #     done
+      #     echo "Failed to reach frontend after $MAX_RETRIES attempts."
+      #     exit 1
+      #   name: frontend-check
+      #   securityContext:
+      #     allowPrivilegeEscalation: false
+      #     capabilities:
+      #       drop:
+      #         - ALL
+      #     privileged: false
+      #     readOnlyRootFilesystem: true
+      #   image: curlimages/curl:latest
+      #   env:
+      #   - name: FRONTEND_ADDR
+      #     value: "frontend:80"
       containers:
       - name: main
         securityContext:
